exclude: '^$'
fail_fast: false
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
    -   id: check-xml
    -   id: check-added-large-files
        args: ['--maxkb=1600']
    -   id: debug-statements
    -   id: check-merge-conflict

-   repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

-   repo: 'https://github.com/ambv/black'
    rev: 20.8b1
    hooks:
    -   id: black
        args: ['--safe']

-   repo: 'https://github.com/chewse/pre-commit-mirrors-pydocstyle'
    rev: v2.1.1
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    -   id: isort
