exclude: '^$'
fail_fast: false
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: ^charts/eodag-server/templates/
    -   id: check-xml
    -   id: check-added-large-files
        args: ['--maxkb=1600']
    -   id: debug-statements
    -   id: check-merge-conflict

-   repo: 'https://github.com/PyCQA/flake8'
    rev: 6.1.0 # needed for py < 3.8.1
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-eradicate

-   repo: 'https://github.com/ambv/black'
    rev: 22.12.0
    hooks:
    -   id: black
        args: ['--safe']

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
